# Config file for automatic testing at travis-ci.org

language: python
python:
  
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
    - sudo add-apt-repository universe
    - sudo apt-get update

# command to install dependencies
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install -y -c conda-forge python-igraph
  - conda install -y -c anaconda flask
  - conda install -y -c conda-forge flask-restplus
  - pip install coveralls
  - pip install .
# command to run tests
script: coverage run --source w2v_tissues setup.py test

after_success: coveralls
